import type { NavModuleDefinition } from "@school-clerk/navigation";

export const dashboardNavRegistry: NavModuleDefinition[] = [
  {
    icon: "graduation-cap",
    key: "teacher-workspace",
    sections: [
      {
        items: [
          {
            childPaths: ["/teacher"],
            href: "/teacher",
            icon: "dashboard",
            key: "teacher-overview",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "dashboard",
            title: "Overview",
            workspace: "teacher",
          },
        ],
        key: "dashboard",
      },
      {
        items: [
          {
            href: "/teacher/classes",
            icon: "list",
            key: "teacher-classes",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "My Classes",
            workspace: "teacher",
          },
          {
            href: "/teacher/students",
            icon: "users",
            key: "teacher-students",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "My Students",
            workspace: "teacher",
          },
          {
            href: "/teacher/attendance",
            icon: "calendar-check",
            key: "teacher-attendance",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "Attendance",
            workspace: "teacher",
          },
        ],
        key: "main",
        title: "Classroom Work",
      },
      {
        items: [
          {
            href: "/teacher/assessments",
            icon: "clipboard-list",
            key: "teacher-assessments",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "Assessments",
            workspace: "teacher",
          },
          {
            href: "/teacher/grading",
            icon: "award",
            key: "teacher-grading",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "Grading",
            workspace: "teacher",
          },
          {
            href: "/teacher/reports",
            icon: "file-text",
            key: "teacher-reports",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "Reports",
            workspace: "teacher",
          },
          {
            href: "/teacher/timetable",
            icon: "calendar",
            key: "teacher-timetable",
            module: "teacher-workspace",
            roles: ["Teacher"],
            section: "main",
            title: "Timetable",
            workspace: "teacher",
          },
        ],
        key: "main",
        title: "Assessment",
      },
    ],
    subtitle: "Teacher Workspace",
    title: "Teacher",
    workspace: "teacher",
  },
  {
    icon: "school",
    key: "home",
    sections: [
      {
        items: [
          {
            href: "/dashboard",
            icon: "dashboard",
            key: "dashboard-home",
            module: "home",
            roles: ["Admin", "Staff"],
            section: "main",
            title: "Dashboard",
            workspace: "admin",
          },
          {
            href: "/notifications",
            icon: "bell",
            key: "notifications",
            module: "home",
            roles: [
              "Admin",
              "Teacher",
              "Accountant",
              "Registrar",
              "HR",
              "Staff",
              "Support",
            ],
            section: "main",
            title: "Notifications",
            workspace: "admin",
          },
          {
            href: "/announcements",
            icon: "speaker",
            key: "announcements",
            module: "home",
            roles: ["Admin", "Teacher"],
            section: "main",
            status: "upcoming",
            title: "Announcements",
            workspace: "admin",
          },
          {
            href: "/calendar",
            icon: "calendar",
            key: "calendar",
            module: "home",
            roles: ["Admin", "Teacher", "Staff"],
            section: "main",
            status: "upcoming",
            title: "Calendar",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "General",
      },
    ],
    subtitle: "School Management",
    title: "Home",
    workspace: "admin",
  },
  {
    icon: "users",
    key: "students",
    sections: [
      {
        items: [
          {
            href: "/students/list",
            icon: "users",
            key: "students-list",
            module: "students",
            roles: ["Admin"],
            section: "main",
            title: "Students",
            workspace: "admin",
          },
          {
            href: "/students/enrollment",
            icon: "user-plus",
            key: "students-enrollment",
            module: "students",
            roles: ["Admin", "Registrar"],
            section: "main",
            title: "Enrollment",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Student Management",
      },
    ],
    subtitle: "Admissions & Records",
    title: "Students",
    workspace: "admin",
  },
  {
    icon: "graduation-cap",
    key: "academics",
    sections: [
      {
        items: [
          {
            childPaths: ["/academic"],
            href: "/academic",
            icon: "dashboard",
            key: "academic-dashboard",
            module: "academics",
            roles: ["Admin"],
            section: "dashboard",
            title: "Dashboard",
            workspace: "admin",
          },
        ],
        key: "dashboard",
      },
      {
        items: [
          {
            href: "/academic/classes",
            icon: "list",
            key: "academic-classes",
            module: "academics",
            roles: ["Admin"],
            section: "main",
            title: "Classes",
            workspace: "admin",
          },
          {
            href: "/academic/subjects",
            icon: "book",
            key: "academic-subjects",
            module: "academics",
            roles: ["Admin"],
            section: "main",
            title: "Subjects",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Curriculum",
      },
      {
        items: [
          {
            href: "/academic/assessments",
            icon: "clipboard-list",
            key: "academic-assessments",
            module: "academics",
            roles: ["Admin"],
            section: "main",
            status: "upcoming",
            title: "Tests & Exams",
            workspace: "admin",
          },
          {
            href: "/academic/grading",
            icon: "award",
            key: "academic-grading",
            module: "academics",
            roles: ["Admin"],
            section: "main",
            status: "upcoming",
            title: "Grading",
            workspace: "admin",
          },
          {
            href: "/academic/reports",
            icon: "file-text",
            key: "academic-reports",
            module: "academics",
            roles: ["Admin"],
            section: "main",
            status: "upcoming",
            title: "Report Cards",
            workspace: "admin",
          },
          {
            href: "/student-report",
            icon: "bar-chart-2",
            key: "academic-student-report",
            module: "academics",
            roles: ["Admin"],
            section: "main",
            title: "Student Report",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Assessment",
      },
    ],
    subtitle: "Academic Operations",
    title: "Academics",
    workspace: "admin",
  },
  {
    icon: "wallet",
    key: "finance",
    sections: [
      {
        items: [
          {
            href: "/finance",
            icon: "dashboard",
            key: "finance-overview",
            module: "finance",
            roles: ["Admin"],
            section: "dashboard",
            title: "Overview",
            workspace: "admin",
          },
        ],
        key: "dashboard",
      },
      {
        items: [
          {
            children: [
              {
                href: "/finance/streams",
                key: "finance-streams",
                module: "finance",
                roles: ["Admin"],
                section: "main",
                title: "Account Streams",
                workspace: "admin",
              },
              {
                href: "/finance/payments",
                key: "finance-payments",
                module: "finance",
                roles: ["Admin", "Accountant"],
                section: "main",
                title: "Remuneration",
                workspace: "admin",
              },
              {
                href: "/staff/payroll",
                key: "finance-payroll",
                module: "finance",
                roles: ["Admin"],
                section: "main",
                title: "Payroll",
                workspace: "admin",
              },
              {
                href: "/finance/transactions",
                key: "finance-transactions",
                module: "finance",
                roles: ["Admin", "Accountant"],
                section: "main",
                title: "Transactions",
                workspace: "admin",
              },
            ],
            href: "/finance/streams",
            icon: "layers",
            key: "finance-accounting",
            module: "finance",
            roles: ["Admin"],
            section: "main",
            title: "Accounting",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Accounting",
      },
      {
        items: [
          {
            href: "/finance/fees-management",
            icon: "coins",
            key: "finance-fees-management",
            module: "finance",
            roles: ["Admin"],
            section: "main",
            title: "Fee Management",
            workspace: "admin",
          },
          {
            href: "/finance/billables",
            icon: "coins",
            key: "finance-billables",
            module: "finance",
            roles: ["Admin"],
            section: "main",
            title: "Service Billables",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Configuration",
      },
      {
        items: [
          {
            href: "/finance/student-fees",
            icon: "file-text",
            key: "finance-student-fees",
            module: "finance",
            roles: ["Admin", "Accountant"],
            section: "main",
            title: "Student Fees",
            workspace: "admin",
          },
          {
            href: "/finance/collections",
            icon: "trending-up",
            key: "finance-collections",
            module: "finance",
            roles: ["Admin", "Accountant"],
            section: "main",
            title: "Collections",
            workspace: "admin",
          },
          {
            href: "/finance/bills",
            icon: "file-text",
            key: "finance-bills",
            module: "finance",
            roles: ["Admin", "Accountant"],
            section: "main",
            title: "Bills",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Payments",
      },
    ],
    subtitle: "Finance & Payments",
    title: "Finance",
    workspace: "admin",
  },
  {
    icon: "users",
    key: "staff",
    sections: [
      {
        items: [
          {
            href: "/staff/teachers",
            icon: "users",
            key: "staff-teachers",
            module: "staff",
            roles: ["Admin"],
            section: "main",
            title: "Teachers",
            workspace: "admin",
          },
          {
            href: "/staff/non-teaching",
            icon: "users",
            key: "staff-non-teaching",
            module: "staff",
            roles: ["Admin", "HR"],
            section: "main",
            title: "Non-Teaching Staff",
            workspace: "admin",
          },
          {
            href: "/staff/departments",
            icon: "building",
            key: "staff-departments",
            module: "staff",
            roles: ["Admin", "HR"],
            section: "main",
            title: "Departments",
            workspace: "admin",
          },
          {
            href: "/staff/attendance",
            icon: "calendar-check",
            key: "staff-attendance",
            module: "staff",
            roles: ["Admin", "HR"],
            section: "main",
            title: "Attendance",
            workspace: "admin",
          },
          {
            href: "/staff/payroll",
            icon: "wallet",
            key: "staff-payroll",
            module: "staff",
            roles: ["Admin"],
            section: "main",
            title: "Payroll",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Staff Management",
      },
    ],
    subtitle: "HR & Staff",
    title: "Staff",
    workspace: "admin",
  },
  {
    icon: "package",
    key: "operations",
    sections: [
      {
        items: [
          {
            href: "/inventory",
            icon: "package",
            key: "operations-inventory",
            module: "operations",
            roles: ["Admin", "Accountant"],
            section: "main",
            title: "Inventory",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Operations",
      },
    ],
    subtitle: "Campus Operations",
    title: "Operations",
    workspace: "admin",
  },
  {
    icon: "user",
    key: "parent-portal",
    sections: [
      {
        items: [
          {
            href: "/parents/performance",
            icon: "bar-chart",
            key: "parent-performance",
            module: "parent-portal",
            roles: ["Parent"],
            section: "main",
            status: "upcoming",
            title: "Student Performance",
            workspace: "parent",
          },
          {
            href: "/parents/messages",
            icon: "message-square",
            key: "parent-messages",
            module: "parent-portal",
            roles: ["Parent"],
            section: "main",
            status: "upcoming",
            title: "Communication",
            workspace: "parent",
          },
          {
            href: "/parents/payments",
            icon: "credit-card",
            key: "parent-payments",
            module: "parent-portal",
            roles: ["Parent"],
            section: "main",
            status: "upcoming",
            title: "Payments",
            workspace: "parent",
          },
        ],
        key: "main",
        title: "Engagement",
      },
    ],
    subtitle: "Parent Experience",
    title: "Parent Portal",
    workspace: "parent",
  },
  {
    icon: "settings",
    key: "settings",
    sections: [
      {
        items: [
          {
            href: "/settings/school-profile",
            icon: "settings",
            key: "settings-school-profile",
            module: "settings",
            roles: ["Admin"],
            section: "main",
            title: "School Profile",
            workspace: "admin",
          },
          {
            href: "/settings/sessions",
            icon: "calendar",
            key: "settings-sessions",
            module: "settings",
            roles: ["Admin"],
            section: "main",
            status: "upcoming",
            title: "Academic Session",
            workspace: "admin",
          },
          {
            href: "/settings/roles",
            icon: "shield",
            key: "settings-roles",
            module: "settings",
            roles: ["Admin"],
            section: "main",
            status: "upcoming",
            title: "Roles & Permissions",
            workspace: "admin",
          },
        ],
        key: "main",
        title: "Configuration",
      },
    ],
    subtitle: "Configuration",
    title: "Settings",
    workspace: "admin",
  },
];
