import type { NavModuleDefinition } from "@school-clerk/navigation";

export const academicsNavigationModule: NavModuleDefinition = {
	icon: "school",
	key: "academics",
	sections: [
		{
			items: [
				{
					childPaths: ["/academic"],
					href: "/academic",
					icon: "dashboard",
					key: "academic-dashboard",
					module: "academics",
					roles: ["Admin"],
					section: "dashboard",
					title: "Overview",
					workspace: "admin",
				},
			],
			key: "dashboard",
		},
		{
			items: [
				{
					childPaths: ["/academic/classes"],
					href: "/academic/classes",
					icon: "list",
					key: "academic-classes",
					module: "academics",
					roles: ["Admin"],
					section: "curriculum",
					title: "Classes",
					workspace: "admin",
				},
				{
					childPaths: ["/academic/subjects"],
					href: "/academic/subjects",
					icon: "book",
					key: "academic-subjects",
					module: "academics",
					roles: ["Admin"],
					section: "curriculum",
					title: "Subjects",
					workspace: "admin",
				},
			],
			key: "curriculum",
			title: "Curriculum",
		},
		{
			items: [
				{
					href: "/assessment-recording",
					icon: "edit",
					key: "academic-assessment-recording",
					module: "academics",
					roles: ["Admin"],
					section: "assessment-results",
					title: "Assessment Recording",
					workspace: "admin",
				},
				{
					childPaths: ["/academic/reports"],
					href: "/academic/reports",
					icon: "post",
					key: "academic-reports",
					module: "academics",
					roles: ["Admin"],
					section: "assessment-results",
					title: "Class Report Sheets",
					workspace: "admin",
				},
				{
					href: "/student-report",
					icon: "lineChart",
					key: "academic-student-report",
					module: "academics",
					roles: ["Admin"],
					section: "assessment-results",
					title: "Student Reports",
					workspace: "admin",
				},
				{
					href: "/academic/assessments",
					icon: "edit",
					key: "academic-assessments",
					module: "academics",
					roles: ["Admin"],
					section: "assessment-results",
					status: "upcoming",
					title: "Tests & Exams",
					workspace: "admin",
				},
				{
					href: "/academic/grading",
					icon: "award",
					key: "academic-grading",
					module: "academics",
					roles: ["Admin"],
					section: "assessment-results",
					status: "upcoming",
					title: "Grading",
					workspace: "admin",
				},
			],
			key: "assessment-results",
			title: "Assessment & Results",
		},
	],
	subtitle: "Academic Operations",
	title: "Academics",
	workspace: "admin",
};
