import type { NavModuleDefinition } from "@school-clerk/navigation";

export const financeNavigationModule: NavModuleDefinition = {
	icon: "wallet",
	key: "finance",
	sections: [
		{
			items: [
				{
					childPaths: ["/finance"],
					href: "/finance",
					icon: "dashboard",
					key: "finance-overview",
					module: "finance",
					roles: ["Admin"],
					section: "dashboard",
					title: "Overview",
					workspace: "finance-office",
				},
			],
			key: "dashboard",
		},
		{
			items: [
				{
					href: "/finance/receive",
					icon: "billing",
					key: "finance-receive-payment",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "collections",
					title: "Receive Payment",
					workspace: "finance-office",
				},
				{
					childPaths: ["/finance/students"],
					href: "/finance/students",
					icon: "users",
					key: "finance-student-balances",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "collections",
					title: "Student Balances",
					workspace: "finance-office",
				},
				{
					childPaths: ["/finance/collections"],
					href: "/finance/collections",
					icon: "TrendingUp",
					key: "finance-collections",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "collections",
					title: "Collections",
					workspace: "finance-office",
				},
			],
			key: "collections",
			title: "Collections",
		},
		{
			items: [
				{
					childPaths: ["/finance/payables"],
					href: "/finance/payables",
					icon: "post",
					key: "finance-payables",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "payables",
					title: "All Payables",
					workspace: "finance-office",
				},
				{
					href: "/finance/payables/payroll",
					icon: "billing",
					key: "finance-payroll-bills",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "payables",
					title: "Payroll Bills",
					workspace: "finance-office",
				},
				{
					href: "/finance/payables/services",
					icon: "package",
					key: "finance-service-bills",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "payables",
					title: "Service Bills",
					workspace: "finance-office",
				},
				{
					href: "/finance/payables/owing",
					icon: "wallet",
					key: "finance-owing-repayments",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "payables",
					title: "Owing & Repayments",
					workspace: "finance-office",
				},
			],
			key: "payables",
			title: "Payables",
		},
		{
			items: [
				{
					childPaths: ["/finance/accounts"],
					href: "/finance/accounts",
					icon: "layers",
					key: "finance-streams",
					module: "finance",
					roles: ["Admin"],
					section: "accounting",
					title: "Accounts",
					workspace: "finance-office",
				},
				{
					childPaths: ["/finance/accounts/transfers"],
					href: "/finance/accounts/transfers",
					icon: "Transactions2",
					key: "finance-transfers",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "accounting",
					title: "Transfers",
					workspace: "finance-office",
				},
				{
					childPaths: ["/finance/ledger"],
					href: "/finance/ledger",
					icon: "reciept",
					key: "finance-ledger",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "accounting",
					title: "Ledger",
					workspace: "finance-office",
				},
				{
					childPaths: ["/finance/reconciliation"],
					href: "/finance/reconciliation",
					icon: "check",
					key: "finance-reconciliation",
					module: "finance",
					roles: ["Admin", "Accountant"],
					section: "accounting",
					title: "Reconciliation",
					workspace: "finance-office",
				},
			],
			key: "accounting",
			title: "Accounting",
		},
		{
			items: [
				{
					href: "/finance/setup/fees",
					icon: "coins",
					key: "finance-fee-structures",
					module: "finance",
					roles: ["Admin"],
					section: "finance-setup",
					title: "Fee Structures",
					workspace: "finance-office",
				},
				{
					href: "/finance/setup/service-billables",
					icon: "package",
					key: "finance-service-billables",
					module: "finance",
					roles: ["Admin"],
					section: "finance-setup",
					title: "Service Billables",
					workspace: "finance-office",
				},
			],
			key: "finance-setup",
			title: "Setup",
		},
	],
	subtitle: "Accounts & Finance",
	title: "Finance",
	workspace: "finance-office",
};
