import type { NavModuleDefinition } from "@school-clerk/navigation";

export const peopleNavigationModule: NavModuleDefinition = {
	icon: "users",
	key: "people",
	sections: [
		{
			items: [
				{
					childPaths: ["/students"],
					href: "/students/list",
					icon: "users",
					key: "students-list",
					module: "people",
					roles: ["Admin", "Registrar"],
					section: "student-records",
					title: "Students",
					workspace: "people",
				},
				{
					href: "/students/enrollment",
					icon: "add",
					key: "students-enrollment",
					module: "people",
					roles: ["Admin", "Registrar"],
					section: "student-records",
					title: "Enrollment",
					workspace: "people",
				},
			],
			key: "student-records",
			title: "Student Records",
		},
		{
			items: [
				{
					href: "/staff/teachers",
					icon: "users",
					key: "staff-teachers",
					module: "people",
					roles: ["Admin"],
					section: "staff",
					title: "Teachers",
					workspace: "people",
				},
				{
					href: "/staff/non-teaching",
					icon: "users",
					key: "staff-non-teaching",
					module: "people",
					roles: ["Admin", "HR"],
					section: "staff",
					title: "Non-Teaching Staff",
					workspace: "people",
				},
				{
					href: "/staff/departments",
					icon: "building",
					key: "staff-departments",
					module: "people",
					roles: ["Admin", "HR"],
					section: "staff",
					title: "Departments",
					workspace: "people",
				},
			],
			key: "staff",
			title: "Staff",
		},
		{
			items: [
				{
					href: "/staff/attendance",
					icon: "calendar",
					key: "staff-attendance",
					module: "people",
					roles: ["Admin", "HR"],
					section: "workforce",
					title: "Staff Attendance",
					workspace: "people",
				},
				{
					href: "/staff/payroll",
					icon: "wallet",
					key: "staff-payroll",
					module: "people",
					roles: ["Admin"],
					section: "workforce",
					status: "upcoming",
					title: "Payroll",
					workspace: "people",
				},
			],
			key: "workforce",
			title: "Workforce",
		},
	],
	subtitle: "Students & Staff",
	title: "People",
	workspace: "people",
};
