import type { NavModuleDefinition } from "@school-clerk/navigation";

export const teacherNavigationModule: NavModuleDefinition = {
	icon: "school",
	key: "teacher-workspace",
	sections: [
		{
			items: [
				{
					childPaths: ["/teacher"],
					href: "/teacher",
					icon: "dashboard",
					key: "teacher-overview",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "dashboard",
					title: "Overview",
					workspace: "teacher",
				},
			],
			key: "dashboard",
		},
		{
			items: [
				{
					childPaths: ["/teacher/classes"],
					href: "/teacher/classes",
					icon: "list",
					key: "teacher-classes",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "classroom-work",
					title: "My Classes",
					workspace: "teacher",
				},
				{
					childPaths: ["/teacher/students"],
					href: "/teacher/students",
					icon: "users",
					key: "teacher-students",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "classroom-work",
					title: "My Students",
					workspace: "teacher",
				},
				{
					childPaths: ["/teacher/attendance"],
					href: "/teacher/attendance",
					icon: "calendar",
					key: "teacher-attendance",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "classroom-work",
					title: "Attendance",
					workspace: "teacher",
				},
			],
			key: "classroom-work",
			title: "Classroom Work",
		},
		{
			items: [
				{
					href: "/assessment-recording",
					icon: "edit",
					key: "teacher-score-entry",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "assessment-results",
					title: "Score Entry",
					workspace: "teacher",
				},
				{
					childPaths: ["/teacher/reports"],
					href: "/teacher/reports",
					icon: "post",
					key: "teacher-reports",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "assessment-results",
					title: "Reports",
					workspace: "teacher",
				},
				{
					href: "/teacher/assessments",
					icon: "edit",
					key: "teacher-assessments",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "assessment-results",
					status: "upcoming",
					title: "Assessments",
					workspace: "teacher",
				},
				{
					href: "/teacher/grading",
					icon: "award",
					key: "teacher-grading",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "assessment-results",
					status: "upcoming",
					title: "Grading",
					workspace: "teacher",
				},
			],
			key: "assessment-results",
			title: "Assessment & Results",
		},
		{
			items: [
				{
					href: "/teacher/timetable",
					icon: "calendar",
					key: "teacher-timetable",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "school",
					status: "upcoming",
					title: "Timetable",
					workspace: "teacher",
				},
				{
					href: "/announcements",
					icon: "speaker",
					key: "teacher-announcements",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "school",
					status: "upcoming",
					title: "Announcements",
					workspace: "teacher",
				},
				{
					href: "/calendar",
					icon: "calendar",
					key: "teacher-calendar",
					module: "teacher-workspace",
					roles: ["Teacher"],
					section: "school",
					status: "upcoming",
					title: "Calendar",
					workspace: "teacher",
				},
			],
			key: "school",
			title: "School",
		},
	],
	subtitle: "Teacher Workspace",
	title: "Teaching",
	workspace: "teacher",
};
